title: Site officiel de l'atelier 3P
logo: images/logo-atelier3P.png
description: Ceci est la page officielle de l'Atelier Programmation Python Pratique (A-3P)
show_downloads: true
google_analytics:
theme: jekyll-theme-dinky
